#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [[ -h "${SOURCE}" ]]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "${SOURCE}" )" >/dev/null && pwd )"
    SOURCE="$(readlink "${SOURCE}")"
    # if $SOURCE was a relative symlink, we need to resolve it relative to the
    # path where the symlink file was located
    [[ "${SOURCE}" != /* ]] && SOURCE="${DIR}/${SOURCE}"
done
APP_DIR="$( cd -P "$( dirname "${SOURCE}" )" >/dev/null && pwd )"

cd "${APP_DIR}"

# Use Rbenv if available, fallback to system ruby if not:
if [[ -x "${HOME}/.rbenv/shims/ruby" ]] ; then
    exec "${HOME}/.rbenv/shims/ruby" ./main.rb
elif type ruby &>/dev/null; then
    exec ruby ./main.rb
else
    exec notify-send -u critical "Barabara" "No Ruby runtime found!"
    exit 1
fi
